version: 0.2

phases:
  build:
    commands:
      - echo start build at `date`
      - ./gradlew build
artifacts:
  type: zip
  files:
    - ./appspec.yml
    # - ./hooks/restart.sh
    - ./build/libs/cicd-poc.jar
  name: artifact
  discard-paths: yes