version: 0.2

phases:
  pre_build:
    commands:
      - echo If needing exist before testing, here writing.
      - chmod +x gradlew

  build:
    commands:
      - echo "Starting gradle build..."
      - ./gradlew build --info
      - echo "Gradle build finished successfully!"
